In [11]:
import numpy as np

# Завдання 1: Одновимірний масив з першими 10 натуральними числами
vector = np.arange(1, 11)
print("Завдання 1: Вектор з першими 10 натуральними числами:", vector)

# Завдання 2: Двовимірний масив (матриця) розміром 3x3 з нулями
matrix_zeros = np.zeros((3, 3))
print("\nЗавдання 2: Двовимірний масив (3x3) з нулями:\n", matrix_zeros)

# Завдання 3: Масив розміром 5x5 з випадковими цілими числами від 1 до 10
matrix_random_int = np.random.randint(1, 11, (5, 5))
print("\nЗавдання 3: Масив (5x5) з випадковими цілими числами (від 1 до 10):\n", matrix_random_int)

# Завдання 4: Масив розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1
matrix_random_float = np.random.rand(4, 4)
print("\nЗавдання 4: Масив з випадковими дійсними числами (від 0 до 1):\n", matrix_random_float)

# Завдання 5: Два одновимірних масиви розміром 5 з випадковими цілими числами в діапазоні від 1 до 10
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)
# Виконання поелементних операцій над масивами
addition = np.add(array1, array2)
subtraction = np.subtract(array1, array2)
multiplication = np.multiply(array1, array2)
print("\nЗавдання 5:")
print("\nОдномірний масив array1 з довільними цілими числами:\n", array1)
print("\nОдномірний масив array2 з довільними цілими числами:\n", array2)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)

# Завдання 6: Два вектори розміром 7 з довільними числами для знаходження скалярного добутку
vector1 = np.random.randint(1, 11, 7)
vector2 = np.random.randint(1, 11, 7)
scalar_product = np.dot(vector1, vector2)
print("\nЗавдання 6: Вектор vector1 з довільними цілими числами:\n", vector1)
print("\nВектор vector2 з довільними цілими числами:\n", vector2)
print("\nСкалярний добуток:", scalar_product)

# Завдання 7: Дві матриці розміром 2x2 та 2x3 з випадковими цілими числами в діапазоні від 1 до 10
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))
# Перемноження матриць
matrix_product = np.dot(matrix1, matrix2)
print("\nЗавдання 7: Матриця matrix_1 (2x2) з довільними цілими числами:\n", matrix1)
print("\nМатриця matrix_2 (2x3) з довільними цілими числами:\n", matrix2)
print("Результат перемноження двох матриць:\n", matrix_product)

# Завдання 8: Матриця розміром 3x3 з випадковими цілими числами в діапазоні від 1 до 10 та знаходження оберненої матриці
matrix_3x3 = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3)
print("\nЗавдання 8:")
print("Матриця:\n", matrix_3x3)
print("Обернена матриця:\n", inverse_matrix)

# Завдання 9: Матриця розміром 4x4 з випадковими дійсними числами в діапазоні від 0 до 1 та транспонування
matrix_4x4 = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix_4x4)
print("\nЗавдання 9: Матриця matrix_4x4 з числами від 0 до 1:\n", matrix_4x4)
print("Транспонована матриця:\n", transposed_matrix)

# Завдання 10: Створення матриці розміром 3x4 та вектора розміром 4
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector_4 = np.random.randint(1, 11, 4)
# Перемноження матриці на вектор
result = np.dot(matrix_3x4, vector_4)
print("\nЗавдання 10:")
print("Матриця matrix_3x4 з довільними цілими числами:\n", matrix_3x4)
print("Вектор vector_4 з довільними цілими числами:\n", vector_4)
print("Результат перемноження матриці на вектор:\n", result)

# Завдання 11: Створення матриці розміром 2x3 та вектора розміром 3
matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
# Перемноження матриці на вектор
result = np.dot(matrix_2x3, vector_3)
print("\nЗавдання 11:")
print("Матриця matrix_2x3 з числами від 0 до 1:\n", matrix_2x3)
print("Вектор vector_3 з числами від 0 до 1:\n", vector_3)
print("Результат перемноження матриці на вектор:\n", result)

# Завдання 12: Поелементне множення двох матриць розміром 2x2
matrix1_2x2 = np.random.randint(1, 11, (2, 2))
matrix2_2x2 = np.random.randint(1, 11, (2, 2))
elementwise_multiplication = np.multiply(matrix1_2x2, matrix2_2x2)
print("\nЗавдання 12:")
print("Матриця matrix1_2x2 з довільними цілими числами:\n", matrix1_2x2)
print("Матриця matrix2_2x2 з довільними цілими числами:\n", matrix2_2x2)
print("Поелементне множення двох матриць:\n", elementwise_multiplication)

# Завдання 13: Знаходження добутку двох матриць розміром 2x2
product_matrix = np.dot(matrix1_2x2, matrix2_2x2)
print("\nЗавдання 13:")
print("Матриця matrix1_2x2 з довільними цілими числами:\n", matrix1_2x2)
print("Матриця matrix2_2x2 з довільними цілими числами:\n", matrix2_2x2)
#Множення матриць: [[a*e + b*g, a*f + b*h],
#                 [c*e + d*g, c*f + d*h]]
print("Добуток двох матриць:\n", product_matrix)

# Завдання 14: Знаходження суми елементів матриці розміром 5x5
matrix_5x5 = np.random.randint(1, 101, (5, 5))
sum_of_elements = np.sum(matrix_5x5)
print("\nЗавдання 14:")
print("Матриця matrix_5x5 з довільними цілими числами:\n", matrix_5x5)
print("Сума елементів матриці:\n", sum_of_elements)

# Завдання 15: Знаходження різниці двох матриць розміром 4x4
matrix1_4x4 = np.random.randint(1, 11, (4, 4))
matrix2_4x4 = np.random.randint(1, 11, (4, 4))
dif_matrix = np.subtract(matrix1_4x4, matrix2_4x4)
print("\nЗавдання 15:")
print("\nМатриця matrix1_4x4 з довільними цілими числами:\n", matrix1_4x4)
print("\nМатриця matrix2_4x4 з довільними цілими числами:\n", matrix2_4x4)
print("Різниця двох матриць:\n", dif_matrix)

# Завдання 16: Знаходження вектора-стовпчика, що містить суму елементів кожного рядка матриці
matrix_3x3 = np.random.rand(3, 3)
sum_of_rows = np.sum(matrix_3x3, axis=1)
column_vector = sum_of_rows[:, np.newaxis]
print("\nЗавдання 16:")
print("Матриця matrix_3x3 з числами від 0 до 1:\n", matrix_3x3)
print("Вектор-стовпчик з сумою елементів кожного рядка:\n", column_vector)

# Завдання 17: Створення матриці розміром 3x4 з довільними цілими числами та матриці з квадратами цих чисел
matrix_original = np.random.randint(1, 11, (3, 4))
matrix_squares = np.square(matrix_original)
print("\nЗавдання 17:")
print("Матриця (3x4) з довільними цілими числами:\n", matrix_original)
print("Матриця з квадратами чисел:\n", matrix_squares)

# Завдання 18: Знаходження вектора з квадратними коренями цілих чисел випадкового вектора розміром 4
vector_4 = np.random.randint(1, 51, 4)
sqrt_vector = np.sqrt(vector_4)
print("\nЗавдання 18:")
print(f"   vector_4 = {vector_4}\n")
print("Вектор з квадратними коренями чисел:\n", sqrt_vector)

Завдання 1: Вектор з першими 10 натуральними числами: [ 1  2  3  4  5  6  7  8  9 10]

Завдання 2: Двовимірний масив (3x3) з нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Завдання 3: Масив (5x5) з випадковими цілими числами (від 1 до 10):
 [[ 7  8 10 10  4]
 [ 5 10 10 10  7]
 [ 9 10 10  4  4]
 [ 5  8  2  1  2]
 [ 4  5  4  6 10]]

Завдання 4: Масив з випадковими дійсними числами (від 0 до 1):
 [[0.78884492 0.24806866 0.75069818 0.02833679]
 [0.43812785 0.58537753 0.01027908 0.71195799]
 [0.42394354 0.20079465 0.50560009 0.9709385 ]
 [0.65773837 0.41534605 0.46993301 0.92976567]]

Завдання 5:

Одномірний масив array1 з довільними цілими числами:
 [4 8 5 6 9]

Одномірний масив array2 з довільними цілими числами:
 [ 6  9  1 10  4]
Додавання: [10 17  6 16 13]
Віднімання: [-2 -1  4 -4  5]
Множення: [24 72  5 60 36]

Завдання 6: Вектор vector1 з довільними цілими числами:
 [5 4 1 1 9 4 6]

Вектор vector2 з довільними цілими числами:
 [ 9  2  5  7 10 10  4]

Скалярний добуток: 219

Завдання 7