In [19]:
import numpy as np

# 1. Замінити усі непарні числа в arr на -1
arr0 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Завдання 1. Замінити усі непарні числа на -1. Дано: \n", arr0)
arr0[arr0 % 2 != 0] = -1
print("Результат: ", arr0)

# 2. Створити та перетворити 1D-масив на 2D-масив із 2 рядками
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = np.reshape(arr_1d, (2, -1))
print("\nЗавдання 2.Створити та перетворити 1D-масив на 2D-масив із 2 рядками.\n Дано: \n", arr_1d)
print("Результат:\n", arr_2d)

# 3. Створити два двовимірні масиви а і b, та скласти масиви їх вертикально
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
vertical_stack = np.vstack((arr1, arr2))
print("\nЗавдання 3. Створити два двовимірні масиви та скласти масиви їх вертикально.")
print("Перший масив: \n", arr1)
print("Другий масив: \n", arr2)
print("Складені масиви: \n", vertical_stack)

# 4. Створити шаблон без жорсткого кодування
arr1 = np.array([1, 2, 3])
arr_plus_one = np.add(arr1, 1)   # Додати 1 до кожного елемента масиву
arr_times_two = np.multiply(arr1, 2)   # Помножити кожен елемент на 2
arr_sum = np.sum(arr1)   # Обчислити суму всіх елементів масиву
print("\nЗавдання 4. Створити шаблон без жорсткого кодування. Задано масив: \n", arr1)
print("Результати обчислення для шаблонів без жорсткого кодування:")
print("Масив після додавання 1 до кожного елемента:\n", arr_plus_one)
print("Масив після множення кожного елемента на 2:\n", arr_times_two)
print("Сума елементів у масиві:", arr_sum)


# 5. Отримати спільні елементи між a і b
arr1 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr2 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common_elements = np.intersect1d(arr1, arr2)
print("\nЗавдання 5.Отримати спільні елементи для двох векторів. Перший вектор: \n", arr1)
print("Другий вектор:\n", arr2)
print(" Спільні елементи:", common_elements)

# 6. Отримати позиції перших 5 максимальних значень у заданому масиві arr1
np.random.seed(100)  # початкове значення для генератора випадкових чисел NumPy (початкове значення встановлене на 100)
arr1 = np.random.uniform(1, 50, 20)   # uniform генерує випадкові числа (20 чисел) з рівномірного розподілу на вказаному інтервалі
max_indices = np.argsort(arr1)[-5:]  # інструкція сортує масив a в порядку зростання та повертає індекси відповідних елементів, які зберігають порядок сортування
print("\nЗавдання 6.Отримати позиції перших 5 максимальних значень у заданому масиві. Масив: \n", arr1)
reversed_max_indices = max_indices[::-1]
print(" Перші 5 максимальних значення:\n", reversed_max_indices)
selected_values = arr1[reversed_max_indices]
print(" Значення цих елементів:\n", selected_values)

# 7. Вилучити усі значення NaN із одновимірного масиву
    # NaN використовується для позначення відсутності або неможливості обчислити значення
arr1 = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
arr2 = arr1[~np.isnan(arr1)]  # ~np.isnan(arr1) повертає масив булевих значень, в якому True замінено на False, і навпаки
print("\nЗавдання 7. Вилучити усі значення NaN із одновимірного масиву. Масив: \n", arr1)
print(" Усі значення без NaN: \n", arr2)

# 8. Обчислити евклідову відстань між двома масивами a і b
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])
euclidean_distance = np.linalg.norm(arr1 - arr2)
print("\nЗавдання 8. Обчислити евклідову відстань між двома масивами. Масив 1: \n", arr1)
print("Масив 2: \n", arr2)
print(" Результат: \n", euclidean_distance)

# 9. Знайти індекс 5-го повторення числа 1 у масиві x
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
index = np.where(x == 1)[0][4]
print("\nЗавдання 9. Знайти індекс 5-го повторення числа 1 у масиві x. Масив: \n", x)
print(" Результат: \n", index)

# 10. Знайти повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначити їх як True. Перше повторення має бути False.
np.random.seed(100)
a = np.random.randint(0, 5, 10)
is_duplicate = np.full(a.shape[0], False)  # рядок створює масив is_duplicate з тим самим розміром, що і масив a, і заповнює його значеннями False.
_, unique_indices = np.unique(a, return_index=True)  # np.unique дозволяє знайти унікальні значення в масиві та їх індекси першого з'явлення
is_duplicate[unique_indices[1:]] = True  #використовуємо зріз unique_indices[1:], щоб уникнути перевірки першого унікального елемента як дублікату
print("\nЗавдання 10. Знайти повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначити їх як True. Масив: \n", a)
print(" Результат: \n", is_duplicate)

Завдання 1. Замінити усі непарні числа на -1. Дано: 
 [0 1 2 3 4 5 6 7 8 9]
Результат:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]

Завдання 2.Створити та перетворити 1D-масив на 2D-масив із 2 рядками.
 Дано: 
 [1 2 3 4 5 6]
Результат:
 [[1 2 3]
 [4 5 6]]

Завдання 3. Створити два двовимірні масиви та скласти масиви їх вертикально.
Перший масив: 
 [[1 2]
 [3 4]]
Другий масив: 
 [[5 6]
 [7 8]]
Складені масиви: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Завдання 4. Створити шаблон без жорсткого кодування. Задано масив: 
 [1 2 3]
Результати обчислення для шаблонів без жорсткого кодування:
Масив після додавання 1 до кожного елемента:
 [2 3 4]
Масив після множення кожного елемента на 2:
 [2 4 6]
Сума елементів у масиві: 6

Завдання 5.Отримати спільні елементи для двох векторів. Перший вектор: 
 [1 2 3 2 3 4 3 4 5 6]
Другий вектор:
 [ 7  2 10  2  7  4  9  4  9  8]
 Спільні елементи: [2 4]

Завдання 6.Отримати позиції перших 5 максимальних значень у заданому масиві. Масив: 
 [27.62684215 14.64009987 21.80136195 42